# Generated by npm run generate:api-contracts. Do not edit directly.
# Source: api_spec/openapi_v2.yaml

openapi: 3.0.1
info:
  title: sproot
  version: 0.3.0
  description: |
    Sproot is a general purpose environmental management system with a focus on greenhouse and garden. The system is intended to be used to monitor and control various environmental parameters, to  continuously update and maintain "homeostasis". This API is a machine-friendly interface for  interacting with the system, and is designed to be used by a web-based front-end. This specification can be used to generate client libraries, documentation, and other tools.
paths:
  /api/v2/outputs:
    get:
      operationId: listOutputs
      security:
        - bearerAuth: []
        - cookieAuth: []
      tags:
        - Outputs
      summary: Get all outputs.
      description: |
        Returns a list of all outputs. This includes basic information about each output, such as  name, model, and address.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/SuccessResponse"
                  - properties:
                      statusCode:
                        example: 200
                      content:
                        properties:
                          data:
                            items:
                              $ref: "#/components/schemas/OutputBase"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ErrorResponse"
                  - properties:
                      statusCode:
                        example: 401
                      error:
                        properties:
                          name:
                            example: Unauthorized
                          url:
                            example: /api/v2/outputs
                          details:
                            items:
                              example: Invalid or Missing JWT.
    post:
      operationId: createOutput
      security:
        - bearerAuth: []
        - cookieAuth: []
      tags:
        - Outputs
      summary: Add a new output.
      description: |
        Adds a new output to the service, and regenerates the list of outputs. Returns the information used to create the output.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OutputCreateRequest"
      responses:
        "201":
          description: Output created
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/SuccessResponse"
                  - properties:
                      statusCode:
                        example: 201
                      content:
                        properties:
                          data:
                            $ref: "#/components/schemas/OutputCreateResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ErrorResponse"
                  - properties:
                      statusCode:
                        example: 400
                      error:
                        properties:
                          name:
                            example: Bad Request
                          url:
                            example: /api/v2/outputs
                          details:
                            example:
                              - "Missing required field: model"
                              - "Missing required field: address"
                              - "Missing required field: name"
                              - "Missing required field: pin"
                              - "Missing required field: isPwm"
                              - "Missing required field: isInvertedPwm"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ErrorResponse"
                  - properties:
                      statusCode:
                        example: 401
                      error:
                        properties:
                          name:
                            example: Unauthorized
                          url:
                            example: /api/v2/outputs
                          details:
                            example: Invalid or Missing JWT.
        "503":
          description: Service unavailable
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ErrorResponse"
                  - properties:
                      statusCode:
                        example: 503
                      error:
                        properties:
                          name:
                            example: Service Unavailable
                          url:
                            example: /api/v2/outputs
                          details:
                            items:
                              example:
                                - Failed to add output to database.
                                - Database connection failed.
  /api/v2/outputs/{outputId}:
    get:
      operationId: getOutputById
      security:
        - bearerAuth: []
        - cookieAuth: []
      tags:
        - Outputs
      summary: Get an output by Id.
      description: |
        Returns data for the given output. This includes basic information, such as name, model,  and address. Also contains the current state of the output.
      parameters:
        - in: path
          name: outputId
          required: true
          description: Output Id
          schema:
            type: string
          example: "1"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/SuccessResponse"
                  - properties:
                      statusCode:
                        example: 200
                      content:
                        properties:
                          data:
                            items:
                              $ref: "#/components/schemas/OutputBase"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ErrorResponse"
                  - properties:
                      statusCode:
                        example: 401
                      error:
                        properties:
                          name:
                            example: Unauthorized
                          url:
                            example: /api/v2/outputs/1
                          details:
                            items:
                              example: Invalid or Missing JWT.
        "404":
          description: Output not found
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ErrorResponse"
                  - properties:
                      statusCode:
                        example: 404
                      error:
                        properties:
                          name:
                            example: Not Found
                          url:
                            example: /api/v2/outputs/-1
                          details:
                            items:
                              example: Output with ID -1 not found.
    patch:
      operationId: updateOutput
      security:
        - bearerAuth: []
        - cookieAuth: []
      tags:
        - Outputs
      summary: Update an output by Id.
      description: |
        Updates an output with the given ID. This operation changes only the fields provided.
      parameters:
        - in: path
          name: outputId
          required: true
          description: Output Id
          schema:
            type: string
          example: "1"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: PCA9685
                model:
                  type: string
                  example: PCA9685
                address:
                  type: string
                  example: "0x40"
                pin:
                  type: string
                  example: "0"
                isPwm:
                  type: boolean
                  example: true
                isInvertedPwm:
                  type: boolean
                  example: false
                color:
                  type: string
                  example: "#ff0000"
      responses:
        "200":
          description: Output updated
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/SuccessResponse"
                  - properties:
                      statusCode:
                        example: 200
                      content:
                        properties:
                          data:
                            $ref: "#/components/schemas/SDBOutput"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ErrorResponse"
                  - properties:
                      statusCode:
                        example: 400
                      error:
                        properties:
                          name:
                            example: Bad Request
                          url:
                            example: /api/v2/outputs/string
                          details:
                            example:
                              - Invalid or missing output Id.
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ErrorResponse"
                  - properties:
                      statusCode:
                        example: 401
                      error:
                        properties:
                          name:
                            example: Unauthorized
                          url:
                            example: /api/v2/outputs/1
                          details:
                            items:
                              example: Invalid or Missing JWT.
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ErrorResponse"
                  - properties:
                      statusCode:
                        example: 404
                      error:
                        properties:
                          name:
                            example: Not Found
                          url:
                            example: /api/v2/outputs/-1
                          details:
                            items:
                              example: Output with ID -1 not found.
        "503":
          description: Service unavailable
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ErrorResponse"
                  - properties:
                      statusCode:
                        example: 503
                      error:
                        properties:
                          name:
                            example: Service Unavailable
                          url:
                            example: /api/v2/outputs/1
                          details:
                            items:
                              example:
                                - Failed to update output in database.
                                - Database connection failed.
    delete:
      operationId: deleteOutput
      security:
        - bearerAuth: []
        - cookieAuth: []
      tags:
        - Outputs
      summary: Delete an output by Id.
      description: |
        Deletes an output with the given ID. This operation is permanent and cannot be undone.
      parameters:
        - in: path
          name: outputId
          required: true
          description: Output Id
          schema:
            type: string
          example: "1"
      responses:
        "200":
          description: Output deleted
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/SuccessResponse"
                  - properties:
                      statusCode:
                        example: 200
                      content:
                        properties:
                          data:
                            example: Output sucessfully deleted.
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ErrorResponse"
                  - properties:
                      statusCode:
                        example: 400
                      error:
                        properties:
                          name:
                            example: Bad Request
                          url:
                            example: /api/v2/outputs/string
                          details:
                            example:
                              - Invalid or missing output Id.
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ErrorResponse"
                  - properties:
                      statusCode:
                        example: 401
                      error:
                        properties:
                          name:
                            example: Unauthorized
                          url:
                            example: /api/v2/outputs/1
                          details:
                            items:
                              example: Invalid or Missing JWT.
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ErrorResponse"
                  - properties:
                      statusCode:
                        example: 404
                      error:
                        properties:
                          name:
                            example: Not Found
                          url:
                            example: /api/v2/outputs/-1
                          details:
                            items:
                              example: Output with ID -1 not found.
        "503":
          description: Service unavailable
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ErrorResponse"
                  - properties:
                      statusCode:
                        example: 503
                      error:
                        properties:
                          name:
                            example: Service Unavailable
                          url:
                            example: /api/v2/outputs/1
                          details:
                            items:
                              example:
                                - Failed to delete output from database.
                                - Database connection failed.
  /api/v2/outputs/chart-data:
    get:
      operationId: getOutputChartData
      security:
        - bearerAuth: []
        - cookieAuth: []
      tags:
        - Outputs
      summary: Get all chart data.
      parameters:
        - name: latest
          in: query
          description: Return only the latest data point.
          schema:
            type: string
          example: "true"
      description: Returns chart data for all ouputs.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/SuccessResponse"
                  - properties:
                      statusCode:
                        example: 200
                      content:
                        properties:
                          data:
                            type: object
                            properties:
                              data:
                                type: array
                                items:
                                  $ref: "#/components/schemas/DataPoint"
                                example:
                                  - name: 1/24 12:00 am
                                    output1: 0
                                    output2: 50
                                    units: "%"
                                  - name: 1/24 12:05 am
                                    output1: 0
                                    output2: 50
                                    units: "%"
                              series:
                                type: array
                                items:
                                  $ref: "#/components/schemas/ChartSeries"
                                example:
                                  - name: output1
                                    color: lime
                                  - name: output2
                                    color: blue
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ErrorResponse"
                  - properties:
                      statusCode:
                        example: 401
                      error:
                        properties:
                          name:
                            example: Unauthorized
                          url:
                            example: /api/v2/outputs/chart-data
                          details:
                            items:
                              example: Invalid or Missing JWT.
  /api/v2/outputs/supported-models:
    get:
      operationId: listSupportedOutputModels
      security:
        - bearerAuth: []
        - cookieAuth: []
      tags:
        - Outputs
      summary: Get supported models.
      description: |
        Returns a list of supported output models, with the key as the actual model type and the value as the display type. Pass the key to the server where appropriate.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/SuccessResponse"
                  - properties:
                      statusCode:
                        example: 200
                      content:
                        properties:
                          data:
                            allOf:
                              - $ref: "#/components/schemas/SupportedModels"
                            example:
                              object:
                                PCA9685: PCA9685
                                TPLinkSmartPlug: TPLink Smart Plug
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ErrorResponse"
                  - properties:
                      statusCode:
                        example: 401
                      error:
                        properties:
                          name:
                            example: Unauthorized
                          url:
                            example: /api/v2/outputs/supported-models
                          details:
                            items:
                              example: Invalid or Missing JWT.
  /api/v2/outputs/available-devices/{model}:
    get:
      operationId: listAvailableOutputDevices
      security:
        - bearerAuth: []
        - cookieAuth: []
      tags:
        - Outputs
      summary: Gets gets available devices for a given output model.
      description: |
        Gets available devices for a given model. Optionally, filter by address. Useful for getting devices you could create an output with.
      parameters:
        - in: path
          name: model
          required: true
          description: Output model
          schema:
            type: string
          example: TPLINK_SMART_PLUG
        - in: query
          name: address
          required: false
          description: Output address
          schema:
            type: string
          example: 192.168.2.138
        - in: query
          name: filterUsed
          required: false
          description: Output address
          schema:
            type: boolean
          example: false
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/SuccessResponse"
                  - properties:
                      statusCode:
                        example: 200
                      content:
                        properties:
                          data:
                            allOf:
                              - $ref: "#/components/schemas/AvailableDevices"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ErrorResponse"
                  - properties:
                      statusCode:
                        example: 400
                      error:
                        properties:
                          name:
                            example: Bad Request
                          url:
                            example: /api/v2/outputs/available-devices
                          details:
                            example:
                              - Model s300 not recognized.
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ErrorResponse"
                  - properties:
                      statusCode:
                        example: 401
                      error:
                        properties:
                          name:
                            example: Unauthorized
                          url:
                            example: /api/v2/outputs/available-devices
                          details:
                            items:
                              example: Invalid or Missing JWT.
  /api/v2/outputs/{outputId}/control-mode:
    put:
      operationId: setOutputControlMode
      security:
        - bearerAuth: []
        - cookieAuth: []
      tags:
        - Output State
      summary: Set control mode for an output.
      description: |
        Sets the control mode for the output with the given ID. This operation changes the control mode for the output.
      parameters:
        - in: path
          name: outputId
          required: true
          description: Output Id
          schema:
            type: string
          example: "1"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                controlMode:
                  type: string
                  example: manual
      responses:
        "200":
          description: Control mode set
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/SuccessResponse"
                  - properties:
                      statusCode:
                        example: 200
                      content:
                        properties:
                          data:
                            example:
                              - Control mode successfully updated.
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ErrorResponse"
                  - properties:
                      statusCode:
                        example: 400
                      error:
                        properties:
                          name:
                            example: Bad Request
                          url:
                            example: /api/v2/outputs/string/control-mode
                          details:
                            example:
                              - Invalid or missing output Id.
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ErrorResponse"
                  - properties:
                      statusCode:
                        example: 401
                      error:
                        properties:
                          name:
                            example: Unauthorized
                          url:
                            example: /api/v2/outputs/1/control-mode
                          details:
                            items:
                              example: Invalid or Missing JWT.
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ErrorResponse"
                  - properties:
                      statusCode:
                        example: 404
                      error:
                        properties:
                          name:
                            example: Not Found
                          url:
                            example: /api/v2/outputs/-1/control-mode
                          details:
                            items:
                              example: Output with ID -1 not found.
  /api/v2/outputs/{outputId}/manual-state:
    put:
      operationId: setOutputManualState
      security:
        - bearerAuth: []
        - cookieAuth: []
      tags:
        - Output State
      summary: Set manual state for an output.
      description: |
        Sets the manual state for the output with the given ID.
      parameters:
        - in: path
          name: outputId
          required: true
          description: Output Id
          schema:
            type: string
          example: "1"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                value:
                  type: number
                  example: 50
      responses:
        "200":
          description: Manual state set
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/SuccessResponse"
                  - properties:
                      statusCode:
                        example: 200
                      content:
                        properties:
                          data:
                            example:
                              - Manual state successfully updated.
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ErrorResponse"
                  - properties:
                      statusCode:
                        example: 400
                      error:
                        properties:
                          name:
                            example: Bad Request
                          url:
                            example: /api/v2/outputs/string/manual-state
                          details:
                            example:
                              - Invalid or missing output Id.
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ErrorResponse"
                  - properties:
                      statusCode:
                        example: 401
                      error:
                        properties:
                          name:
                            example: Unauthorized
                          url:
                            example: /api/v2/outputs/1/manual-state
                          details:
                            items:
                              example: Invalid or Missing JWT.
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/ErrorResponse"
                  - properties:
                      statusCode:
                        example: 404
                      error:
                        properties:
                          name:
                            example: Not Found
                          url:
                            example: /api/v2/outputs/-1/manual-state
                          details:
                            items:
                              example: Output with ID -1 not found.
components:
  schemas:
    SuccessResponse:
      description: |
        A success response object that is returned by all successful API requests.  Contains a status code, timestamp, a unique request Id, and, optionally, some content.
      allOf:
        - type: object
          properties:
            statusCode:
              type: integer
            content:
              type: object
              required:
                - data
        - $ref: "#/components/schemas/ApiResponse"
    OutputBase:
      description: |
        A basic output object that is returned by the API. This expands upon SDBOutput, including the ID and state of the output. This maps to what the app keeps in memory.
      allOf:
        - $ref: "#/components/schemas/SDBOutput"
        - type: object
          required:
            - id
            - name
            - model
            - address
            - state
          properties:
            id:
              type: number
              example: 1
            state:
              type: object
              properties:
                controlMode:
                  type: string
                  example: manual
                manual:
                  allOf:
                    - $ref: "#/components/schemas/SDBOutputState"
                automatic:
                  allOf:
                    - $ref: "#/components/schemas/SDBOutputState"
    ErrorResponse:
      description: |
        An error response object that is returned by all unsuccessful API requests.  Contains a status code, timestamp, a unique request Id, and an error object. This error object may contain the name of the error, and an array of details (if relevant).
      allOf:
        - type: object
          required:
            - error
          properties:
            statusCode:
              type: integer
            error:
              type: object
              properties:
                request:
                  type: object
                  properties:
                    method:
                      type: string
                    url:
                      type: string
                    body:
                      type: object
                    query:
                      type: object
                name:
                  type: string
                url:
                  type: string
                details:
                  type: array
                  items:
                    type: string
        - $ref: "#/components/schemas/ApiResponse"
    OutputCreateRequest:
      description: |
        Request body for creating an output. Contains only client-writable fields accepted by the create output handler.
      type: object
      required:
        - model
        - address
        - name
        - pin
        - isPwm
        - isInvertedPwm
        - automationTimeout
      properties:
        model:
          type: string
          example: PCA9685
        subcontrollerId:
          nullable: true
          type: number
          example: 1
        address:
          type: string
          example: "0x40"
        name:
          type: string
          example: PCA9685
        pin:
          type: string
          example: "0"
        isPwm:
          type: boolean
          example: true
        isInvertedPwm:
          type: boolean
          example: false
        color:
          type: string
          example: "#ff0000"
        automationTimeout:
          type: number
          example: 60
    OutputCreateResponse:
      description: |
        Transport shape returned by create output. This reflects the handler response before any follow-up read normalization.
      type: object
      required:
        - id
        - model
        - address
        - name
        - pin
        - isPwm
        - isInvertedPwm
        - automationTimeout
      properties:
        id:
          type: number
          example: 1
        model:
          type: string
          example: PCA9685
        subcontrollerId:
          nullable: true
          type: number
          example: 1
        address:
          type: string
          example: "0x40"
        name:
          type: string
          example: PCA9685
        pin:
          type: string
          example: "0"
        isPwm:
          type: boolean
          example: true
        isInvertedPwm:
          type: boolean
          example: false
        color:
          type: string
          example: "#ff0000"
        automationTimeout:
          type: number
          example: 60
    SDBOutput:
      description: |
        An output object that is stored in the database. Contains all the information needed to  create an output, including model, address, name, pin, if the output is a pwm, whether that pwm value is should be inverted, color, and the automation timeout.
      type: object
      required:
        - model
        - address
        - pin
        - isPwm
        - isInvertedPwm
        - color
        - automationTimeout
      properties:
        model:
          type: string
          example: PCA9685
        subcontrollerId:
          nullable: true
          type: number
          example: 1
        address:
          type: string
          example: "0x40"
        name:
          type: string
          example: PCA9685
        pin:
          type: string
          example: "0"
        deviceZoneId:
          nullable: true
          type: number
          example: 1
        parentOutputId:
          nullable: true
          type: number
          example: null
        isPwm:
          type: boolean
          example: true
        isInvertedPwm:
          type: boolean
          example: false
        color:
          type: string
          example: "#ff0000"
        automationTimeout:
          type: number
          example: 60
    DataPoint:
      description: |
        A data point for recharts.
      allOf:
        - type: object
          required:
            - name
          properties:
            name:
              type: string
            units:
              type: string
        - type: object
          additionalProperties:
            oneOf:
              - type: number
              - type: string
    ChartSeries:
      description: |
        An object containing both a name and a color. Used to add flair to a line on a chart.
      type: object
      required:
        - name
        - color
      properties:
        name:
          type: string
        color:
          type: string
    SupportedModels:
      description: |
        A Record of supported device models, mapped to a presentable label.
      type: object
      properties:
        type:
          type: string
    AvailableDevices:
      description: |
        A list of available devices
      type: array
      items:
        type: object
        properties:
          alias:
            type: string
            example: Plug 1
          externalId:
            type: string
            example: 8006C5CA540AABD8165111F62C70CFD3236B0B3703
          address:
            type: string
            example: 192.168.2.138
    ApiResponse:
      description: |
        A generic response object that is returned by all API endpoints. Contains a status code,  timestamp, and a unique request Id.
      type: object
      required:
        - statusCode
        - timestamp
        - requestId
      properties:
        statusCode:
          type: integer
        timestamp:
          type: string
          example: 2021-01-01T00:00:00.000Z
        requestId:
          type: string
          example: 9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d
    SDBOutputState:
      description: |
        An output state object that is stored in the database. Contains all the information needed to  define an output's state, including control mode, value, and log time.
      type: object
      required:
        - value
        - logTime
      properties:
        controlMode:
          type: string
          example: manual
        value:
          type: number
          example: 50
        logTime:
          type: string
          example: 2021-01-01T00:00:00.000Z
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    cookieAuth:
      type: apiKey
      in: cookie
      name: jwt_token
